//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalaqahBlazorApp.Localization.Pages.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Attendance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Attendance() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HalaqahBlazorApp.Localization.Pages.Admin.Attendance", typeof(Attendance).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غائب بعذر.
        /// </summary>
        internal static string AbsentExcused {
            get {
                return ResourceManager.GetString("AbsentExcused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غائب.
        /// </summary>
        internal static string AbsentNotExcused {
            get {
                return ResourceManager.GetString("AbsentNotExcused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل الحضور.
        /// </summary>
        internal static string AttendanceSaveFail {
            get {
                return ResourceManager.GetString("AttendanceSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الحضور.
        /// </summary>
        internal static string AttendanceSaveSuccess {
            get {
                return ResourceManager.GetString("AttendanceSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحضور.
        /// </summary>
        internal static string AttendanceStatus {
            get {
                return ResourceManager.GetString("AttendanceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحضور.
        /// </summary>
        internal static string AttendanceTitle {
            get {
                return ResourceManager.GetString("AttendanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجاز.
        /// </summary>
        internal static string HasCompleted {
            get {
                return ResourceManager.GetString("HasCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماغ.
        /// </summary>
        internal static string HasDress {
            get {
                return ResourceManager.GetString("HasDress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاخر بعذر.
        /// </summary>
        internal static string LateExcused {
            get {
                return ResourceManager.GetString("LateExcused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاخر.
        /// </summary>
        internal static string LateNotExcused {
            get {
                return ResourceManager.GetString("LateNotExcused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاضر.
        /// </summary>
        internal static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل الحضور.
        /// </summary>
        internal static string SaveAttendance {
            get {
                return ResourceManager.GetString("SaveAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطالب.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
    }
}
