// <auto-generated />
using System;
using HalaqahModel.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HalaqahModel.Migrations
{
    [DbContext(typeof(HalaqahContext))]
    partial class HalaqahContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HalaqahModel.Models.Halaqah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("AdminID");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("SemesterID");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("TeacherID");

                    b.Property<int>("WeekDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Halaqah", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.HalaqahRecord", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("StudentID");

                    b.Property<int>("HifzNumPages")
                        .HasColumnType("integer");

                    b.Property<int?>("HifzRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("HifzRecordID");

                    b.Property<int>("HifzTargetNumPages")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("RevisionNumPages")
                        .HasColumnType("integer");

                    b.Property<int?>("RevisionRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("RevisionRecordID");

                    b.Property<int>("RevisionTargetNumPages")
                        .HasColumnType("integer");

                    b.Property<int>("TathbeetNumPages")
                        .HasColumnType("integer");

                    b.Property<int>("TathbeetTargetNumPages")
                        .HasColumnType("integer");

                    b.HasKey("Date", "StudentId")
                        .HasName("PK__tmp_ms_x__F4142FA1F4F98435");

                    b.HasIndex("HifzRecordId");

                    b.HasIndex("RevisionRecordId");

                    b.HasIndex("StudentId");

                    b.ToTable("HalaqahRecord", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.Masjid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Masjid", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("MasjidId")
                        .HasColumnType("integer")
                        .HasColumnName("MasjidID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MasjidId");

                    b.ToTable("Person", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("HalaqahModel.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Record", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.Segment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SegmentID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SegmentId"));

                    b.Property<int>("RecordId")
                        .HasColumnType("integer")
                        .HasColumnName("RecordID");

                    b.Property<int>("AyahFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("AyahTo")
                        .HasColumnType("integer");

                    b.Property<string>("SurahFrom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SurahTo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SegmentId", "RecordId");

                    b.HasIndex("RecordId");

                    b.ToTable("Segment", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Semester", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.SemesterRecord", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("StudentID");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("SemesterID");

                    b.Property<int?>("ExamGrade")
                        .HasColumnType("integer");

                    b.Property<int?>("HifzExistingRecord")
                        .HasColumnType("integer");

                    b.Property<int>("HifzTargetNumPages")
                        .HasColumnType("integer");

                    b.Property<int>("HifzTargetRecord")
                        .HasColumnType("integer");

                    b.Property<int?>("RevisionExistingRecord")
                        .HasColumnType("integer");

                    b.Property<int>("RevisionTargetNumPages")
                        .HasColumnType("integer");

                    b.Property<int>("RevisionTargetRecord")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "SemesterId");

                    b.HasIndex("HifzExistingRecord");

                    b.HasIndex("HifzTargetRecord");

                    b.HasIndex("RevisionExistingRecord");

                    b.HasIndex("RevisionTargetRecord");

                    b.HasIndex("SemesterId");

                    b.ToTable("SemesterRecord", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.StudentAttendance", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("StudentID");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp");

                    b.Property<bool>("HasCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDress")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "Timestamp");

                    b.ToTable("StudentAttendance", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.UserAttendance", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Timestamp")
                        .HasName("PK_Attendance");

                    b.ToTable("UserAttendance", (string)null);
                });

            modelBuilder.Entity("HalaqahStudent", b =>
                {
                    b.Property<int>("HalaqahId")
                        .HasColumnType("integer")
                        .HasColumnName("HalaqahID");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("StudentID");

                    b.HasKey("HalaqahId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("HalaqahStudent", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.Student", b =>
                {
                    b.HasBaseType("HalaqahModel.Models.Person");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("ParentPhone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.User", b =>
                {
                    b.HasBaseType("HalaqahModel.Models.Person");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("boolean");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("HalaqahModel.Models.Halaqah", b =>
                {
                    b.HasOne("HalaqahModel.Models.User", "Admin")
                        .WithMany("HalaqahAdmins")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK_Halaqah_UserAdmin");

                    b.HasOne("HalaqahModel.Models.Semester", "Semester")
                        .WithMany("Halaqahs")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_Halaqah_Semester");

                    b.HasOne("HalaqahModel.Models.User", "Teacher")
                        .WithMany("HalaqahTeachers")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Halaqah_UserTeacher");

                    b.Navigation("Admin");

                    b.Navigation("Semester");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HalaqahModel.Models.HalaqahRecord", b =>
                {
                    b.HasOne("HalaqahModel.Models.Record", "HifzRecord")
                        .WithMany("HalaqahRecordHifzRecords")
                        .HasForeignKey("HifzRecordId")
                        .HasConstraintName("FK_HalaqahRecord_HifzRecord");

                    b.HasOne("HalaqahModel.Models.Record", "RevisionRecord")
                        .WithMany("HalaqahRecordRevisionRecords")
                        .HasForeignKey("RevisionRecordId")
                        .HasConstraintName("FK_HalaqahRecord_RevisionRecord");

                    b.HasOne("HalaqahModel.Models.Student", "Student")
                        .WithMany("HalaqahRecords")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_HalaqahRecord_Student");

                    b.Navigation("HifzRecord");

                    b.Navigation("RevisionRecord");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HalaqahModel.Models.Person", b =>
                {
                    b.HasOne("HalaqahModel.Models.Masjid", "Masjid")
                        .WithMany("People")
                        .HasForeignKey("MasjidId")
                        .IsRequired()
                        .HasConstraintName("FK_Person_Masjid");

                    b.Navigation("Masjid");
                });

            modelBuilder.Entity("HalaqahModel.Models.Segment", b =>
                {
                    b.HasOne("HalaqahModel.Models.Record", "Record")
                        .WithMany("Segments")
                        .HasForeignKey("RecordId")
                        .IsRequired()
                        .HasConstraintName("FK_Segment_Record");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("HalaqahModel.Models.SemesterRecord", b =>
                {
                    b.HasOne("HalaqahModel.Models.Record", "HifzExistingRecordNavigation")
                        .WithMany("SemesterRecordHifzExistingRecordNavigations")
                        .HasForeignKey("HifzExistingRecord")
                        .HasConstraintName("FK_SemesterRecord_HifzExistingRecord");

                    b.HasOne("HalaqahModel.Models.Record", "HifzTargetRecordNavigation")
                        .WithMany("SemesterRecordHifzTargetRecordNavigations")
                        .HasForeignKey("HifzTargetRecord")
                        .IsRequired()
                        .HasConstraintName("FK_SemesterRecord_HifzTargetRecord");

                    b.HasOne("HalaqahModel.Models.Record", "RevisionExistingRecordNavigation")
                        .WithMany("SemesterRecordRevisionExistingRecordNavigations")
                        .HasForeignKey("RevisionExistingRecord")
                        .HasConstraintName("FK_SemesterRecord_RevisionExistingRecord");

                    b.HasOne("HalaqahModel.Models.Record", "RevisionTargetRecordNavigation")
                        .WithMany("SemesterRecordRevisionTargetRecordNavigations")
                        .HasForeignKey("RevisionTargetRecord")
                        .IsRequired()
                        .HasConstraintName("FK_SemesterRecord_RevisionTargetRecord");

                    b.HasOne("HalaqahModel.Models.Semester", "Semester")
                        .WithMany("SemesterRecords")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_SemesterRecord_Semester");

                    b.HasOne("HalaqahModel.Models.Student", "Student")
                        .WithMany("SemesterRecords")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_SemesterRecord_Student");

                    b.Navigation("HifzExistingRecordNavigation");

                    b.Navigation("HifzTargetRecordNavigation");

                    b.Navigation("RevisionExistingRecordNavigation");

                    b.Navigation("RevisionTargetRecordNavigation");

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HalaqahModel.Models.StudentAttendance", b =>
                {
                    b.HasOne("HalaqahModel.Models.Student", "Student")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentAttendance_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HalaqahModel.Models.UserAttendance", b =>
                {
                    b.HasOne("HalaqahModel.Models.User", "User")
                        .WithMany("UserAttendances")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HalaqahStudent", b =>
                {
                    b.HasOne("HalaqahModel.Models.Halaqah", null)
                        .WithMany()
                        .HasForeignKey("HalaqahId")
                        .IsRequired()
                        .HasConstraintName("FK_HalaqahStudent_Halaqah");

                    b.HasOne("HalaqahModel.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_HalaqahStudent_Student");
                });

            modelBuilder.Entity("HalaqahModel.Models.Student", b =>
                {
                    b.HasOne("HalaqahModel.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("HalaqahModel.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalaqahModel.Models.User", b =>
                {
                    b.HasOne("HalaqahModel.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("HalaqahModel.Models.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HalaqahModel.Models.Masjid", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("HalaqahModel.Models.Record", b =>
                {
                    b.Navigation("HalaqahRecordHifzRecords");

                    b.Navigation("HalaqahRecordRevisionRecords");

                    b.Navigation("Segments");

                    b.Navigation("SemesterRecordHifzExistingRecordNavigations");

                    b.Navigation("SemesterRecordHifzTargetRecordNavigations");

                    b.Navigation("SemesterRecordRevisionExistingRecordNavigations");

                    b.Navigation("SemesterRecordRevisionTargetRecordNavigations");
                });

            modelBuilder.Entity("HalaqahModel.Models.Semester", b =>
                {
                    b.Navigation("Halaqahs");

                    b.Navigation("SemesterRecords");
                });

            modelBuilder.Entity("HalaqahModel.Models.Student", b =>
                {
                    b.Navigation("HalaqahRecords");

                    b.Navigation("SemesterRecords");

                    b.Navigation("StudentAttendances");
                });

            modelBuilder.Entity("HalaqahModel.Models.User", b =>
                {
                    b.Navigation("HalaqahAdmins");

                    b.Navigation("HalaqahTeachers");

                    b.Navigation("UserAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
